apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T07:29:45Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "663"
  uid: 7aa811b9-8cf3-4e3f-885b-cfc6f6d08607
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.10.167
  clusterIPs:
  - 10.99.10.167
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30086
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
