apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T06:45:16Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2105"
  uid: 4c49a8e9-6779-46d2-a334-7bf246551f8f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.73.106
  clusterIPs:
  - 10.104.73.106
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32497
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
